### ISSUE TITLE
Features de Pedido

### ISSUE THREAD

**Issue by TeoCalvo** [TeoCalvo/sql-asn#5]
Criação de variáveis sobre os pedidos do Seller

- [x] Quantidade de Pedidos vendidos
- [x] Quantidade de Itens vendidos
- [x] Quantidade de Meses Distintos de venda
- [x] Quantidade de Pedidos postados com atraso
- [x] Média de intervalo entre pedidos (em dias)
- [x] Valor do maior pedido
- [x] Quantidade média de pedidos por mês
- [x] Quantidade média de itens por mês
- [x] Média de proporção do valor de frete por pedido
- [x] Quantidade de Pedidos cancelados
- [x] Razão de quantidade de pedidos mês atual vs mês m-1
- [x] Razão de valor (revenue) de pedidos mês atual vs mês m-1
- [x] Quantidade média de itens por pedido
- [x] Valor médio do frete por pedido
- [x] Total Revenue no período (6m)
- [x] Estado para qual mais vende
~~- [ ] Cidade para qual mais vende~~
- [x] Ticket Médio
- [x] Percentual de vendas por dia da semana
~~- [ ] Distância entre destinatário e remetente~~
~~- [ ] Quantidade de pedidos não aprovados~~
- [x] Percentual de entregas realizadas antes do prazo
- [x] Percentual de entregas realizadas depois do prazo
- [x] Média de dias entre data estimada e data de entrega
- [x] Média de dias entre data de envio e data limite de envio
- [x] Quantidade de estados distintos de entrega

**Comment by inqueen** [comment]
~~- [ ] Quantidade de pedidos não aprovados~~
